name: CI Pipeline for odoo project

on:
  push:
    branches:
      - dev
env:
  IMAGE_NAME: odoo-project
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Run a One-Line Script
      #   run: echo "Hello, world!"
      
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: Validate docker-compose.yml
        run: |
          docker compose -f docker-compose.yml config > /dev/null
          echo "✅ docker-compose.yml is valid"

      - name: Login to GHCR
        run: echo "${{ secrets.TOKEN_GHRC_AM }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/anassamazzar/odoo-project:dev
          docker build -t $IMAGE .
          docker push $IMAGE
