name: CI Pipeline for odoo project

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      # - name: Run a One-Line Script
      #   run: echo "Hello, world!"

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/anassamazzar/odoo-project:dev
          docker build -t $IMAGE .
          docker push $IMAGE


